apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: innodeploy-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: innodeploy-app-dev
            port:
              number: 3000
